backend:
  name: github
  repo: ezzrigal/astro-blog-starter-template
  branch: main
  base_url: https://nqlafshriyadh.com
  auth_endpoint: oauth/auth

media_folder: "public/images/blog"
public_folder: "/images/blog"

locale: en

collections:
  - name: "blog"
    label: "Blog Posts"
    label_singular: "Post"
    folder: "src/content/blog"
    create: true
    delete: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
